name: Job Scraper Weekly

on:
  schedule:
    - cron: "*/1 * * * *"   # Ejecutar cada 5 minutos
    #- cron: "0 7 * * 1"   # Ejecutar todos los lunes a las 08:00 hora España (07:00 UTC)
  workflow_dispatch:

jobs:
  scrape-and-send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run job scraper
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python job_scraper.py
